# Generated by Django 5.1.1 on 2024-12-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
