# Generated by Django 5.1.1 on 2024-12-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0005_contactmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
